# Dockerfile for Target Server

FROM golang:alpine AS builder

# Install necessary packages
RUN apk add --no-cache git

# Download and build gost
RUN go install github.com/ginuerzh/gost/cmd/gost@latest

# Set default environment variables
# ENV SOCKS_PORT=1080
# ENV SOCKS_USER=user
# ENV SOCKS_PASS=pass

# Start gost as a SOCKS5 proxy using environment variables
CMD ["sh", "-c", "gost -L=socks5://$SOCKS_USER:$SOCKS_PASS@:$SOCKS_PORT"]
