FROM gogost/gost

# Set default environment variables
ENV API_USER=api_user
ENV API_PASS=api_pass

# Create GOST configuration file
COPY target_config.json /etc/gost/gost.json

# Expose ports for the services
EXPOSE 80

# Start gost with the custom configuration
CMD ["gost", "-C", "/etc/gost/gost.json"]
